<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stepcounter" nsURI="oxley.dave.fun.sport" nsPrefix="oxley.dave.fun.sport">
  <eClassifiers xsi:type="ecore:EClass" name="Day"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cycle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Target"/>
  <eClassifiers xsi:type="ecore:EClass" name="StepTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="SportTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Status"/>
  <eClassifiers xsi:type="ecore:EClass" name="Punishment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reward"/>
</ecore:EPackage>
